[package]
name = "iota_sc_utils"
version = "0.1.0"
authors = ["Th3B0Y <brunoamancio.ti@gmail.com>"]
edition = "2018"

[dependencies]
wasmlib = { path = "../wasp/contracts/rust/wasmlib" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
